INSERT INTO menuList (cat,nama) VALUES
('Makanan','Chicken Spicy Cheese'),
('Makanan','Ayam Geprek Original'),
('Makanan','Ayam Geprek Cheese'),
('Makanan','Ayam Geprek Cream Cheese'),
('Makanan','Ayam Geprek Mozarella'),
('Makanan','Chicken Rice Bowl Blackpapper'),
('Makanan','Chicken Katsu Teriyaki'),
('Makanan','Chicken Cordon Bleu'),
('Camilan','Chicken Burger Single Chicken'),
('Camilan','Chicken Burger Double Chicken'),
('Camilan','Zuppa Soup'),
('Camilan','Macharoni Schotel'),
('Camilan','Pop Corn'),
('Camilan','Sambosa'),
('Camilan','Sweet Canai'),
('Camilan','French Fries'),
('Camilan','Roti Bakar'),
('Camilan','Chicken Cheese Bals'),
('Camilan','Stick Ball Sosis'),
('Camilan','Pisang Bakar'),
('Camilan','Pisang Bakar Mozarella'),
('Camilan','Siomay Ayam'),
('Camilan','Sosis Blacpapper Cheese'),
('Camilan','Pancace'),
('Camilan','Sandwidch Omah All'),
('Camilan','Bread Toast Ice'),
('Minuman','Ice Tea'),
('Minuman','Jus'),
('Minuman','Lime Tea'),
('Minuman','Taro'),
('Minuman','Green Tea'),
('Minuman','Leci Tea'),
('Minuman','Stroberry Tea'),
('Minuman','Milk Tea'),
('Minuman','Ice Chocolate'),
('Minuman','Ice Coffe'),
('Minuman','Blue Ocean'),
('Minuman','Lime Squash'),
('Minuman','Deep Purple'),
('Minuman','Orange Mint Squash'),
('Minuman','Mojito Virgin'),
('Minuman','Mojito Strawberry'),
('Minuman','Hot Tea'),
('Minuman','Hot Chocolate'),
('Minuman','Kopi Tubruk'),
('Minuman','Kopi V60'),
('Minuman','Kopi French Press'),
('Minuman','Kopi Flat Bottom'),
('Minuman','Kopi Vietnam Drip');
